# Generated by Django 6.0 on 2026-01-02 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
