# Generated by Django 5.2.5 on 2026-01-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_customer_id_alter_product_id_alter_tag_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
